ETTARNI-med/Petify

Backend/controllers/customersController.js, Backend/routes/categories.js, Backend/routes/orders.js, Backend/routes/products.js, Backend/routes/subcategories.js, Backend/routes/users.js
=> i added more routes

Backend/.env, Backend/app.js, Backend/config/jwtToken.js, Backend/controllers/checkAuth.js, Backend/midllewares/errorHandler.js, Backend/models/Category.js, Backend/models/CustomerSchema.js, Backend/models/Order.js, Backend/models/Product.js, Backend/models/SubCategory.js, Backend/models/Users.js, Backend/package-lock.json, Backend/package.json, Backend/routes/customerRoutes.js, Backend/routes/customers.js, Backend/routes/router.js
=> [MES-18]create controllers

Backend/controllers/checkAuth.js, Backend/routes/customerRoutes.js
merge search customer with list all customers
=> [MES-18]merge search customer with list all customers

Backend/controllers/checkAuth.js, Backend/models/CustomerSchema.js
hashing password in the controller instead of Schema
=> [MES-20]hashing password in the controller instead of Schema

Backend/controllers/productsController.js, Backend/routes/products.js
=> add product functions 

Backend/app.js, Backend/controllers/categoriesController.js, Backend/controllers/productsController.js, Backend/controllers/usersController.js, Backend/models/Category.js, Backend/models/Users.js, Backend/routes/categories.js, Backend/routes/router.js, Backend/routes/users.js
=> [MES-23] add 

Backend/controllers/usersController.js, Backend/midllewares/checkUserAuth.js, Backend/routes/users.js
settup middleware and some modification in usercontrollers
=> [MES-26] Settup middleware

Backend/controllers/categoriesController.js, Backend/controllers/checkAuth.js, Backend/controllers/ordersController.js, Backend/controllers/productsController.js, Backend/controllers/subcategoriesController.js, Backend/models/Category.js, Backend/models/Order.js, Backend/models/SubCategory.js, Backend/routes/ordersRoutes.js, Backend/routes/router.js, Backend/routes/subcategories.js
=> [MES-28]add subcategorie

Backend/controllers/usersController.js, Backend/midllewares/checkUserAuth.js, Backend/routes/users.js
=> [MES-30] Set up Get User By Id

Backend/controllers/customersController.js, Backend/controllers/usersController.js, Backend/midllewares/checkUserAuth.js
=> some changes on user middlware

Backend/controllers/usersController.js, Backend/midllewares/checkUserAuth.js, Backend/routes/users.js
Done with Delete user controller
=> [MES-34]. Delete user

Backend/controllers/usersController.js, Backend/midllewares/checkUserAuth.js, Backend/routes/users.js
Done with Update-user controller
=> [MES-37] Set up Update user Controller 

Frontend/src/components/Footer/index.tsx, Frontend/src/components/mode-toggle.tsx
some miner changes in the footer
=> [MES-19] adjust footer

Frontend/src/components/Favorites/SectionHeader.tsx, Frontend/src/components/Favorites/index.tsx
=> [MES-39]Need to adjust breadcrumps

Backend/app.js, Backend/controllers/productsController.js, Backend/controllers/usersController.js, Backend/midllewares/multerMiddleware.js, Backend/package-lock.json, Backend/package.json, Backend/routes/products.js, Backend/routes/users.js
Many modifications in different files
=> [MES-37] Modifications in many files

Backend/.env, Backend/.gitignore, Backend/app.js, Backend/config/sendEmail.js, Backend/config/sendEmailLink.js, Backend/controllers/customersController.js, Backend/controllers/productsController.js, Backend/controllers/usersController.js, Backend/midllewares/checkCustomer.js, Backend/midllewares/checkToken.js, Backend/midllewares/checkUserAuth.js, Backend/midllewares/checkauthCustomer.js, Backend/models/CustomerSchema.js, Backend/models/Product.js, Backend/models/SubCategory.js, Backend/package-lock.json, Backend/package.json, Backend/routes/customerRoutes.js, Backend/routes/products.js, Backend/routes/users.js
add reset password , and other functions
=> [MES-47]add reset password , and other functions

Backend/controllers/usersController.js
=> [MES-51] add controllers

Backend/.env, Backend/config/sendEmail.js, Backend/controllers/customersController.js, Backend/midllewares/checkToken.js, Backend/routes/customerRoutes.js
=> [MES-47]some changes

Backend/app.js, Backend/controllers/customersController.js, Backend/controllers/usersController.js, Backend/midllewares/checkAdmin.js, Backend/midllewares/checkUserAuth.js, Backend/package-lock.json, Backend/package.json, Backend/routes/customerRoutes.js, Backend/routes/users.js
add some functions and modifies others
=> [MES-54]add some functions and modifies others

BackOffice/src/Categories/components/UpdateCategories.tsx, BackOffice/src/Customers/components/AddCustomer.tsx, BackOffice/src/Customers/components/UpdateCustomer.tsx, BackOffice/src/Customers/index.tsx, BackOffice/src/Dashboard/index.tsx, BackOffice/src/Notifications/index.tsx, BackOffice/src/Orders/index.tsx, BackOffice/src/Products/components/AddProduct.tsx, BackOffice/src/Products/components/updateProduct.tsx, BackOffice/src/Products/index.tsx, BackOffice/src/SubCategories/components/AddSubCategories.tsx, BackOffice/src/SubCategories/components/Alert.tsx, BackOffice/src/SubCategories/components/ImageViewer.tsx, BackOffice/src/SubCategories/components/UpdateSubCategories.tsx, BackOffice/src/SubCategories/index.tsx, BackOffice/src/Users/components/AddUser.tsx, BackOffice/src/Users/components/UpdateUser.tsx, BackOffice/src/Users/index.tsx, Backend/controllers/subcategoriesController.js, Backend/models/SubCategory.js, Backend/routes/subcategories.js
make all sections works except the dashboard
=> [MES-59] complete all functionality except dashboard

BackOffice/src/Container/components/user-nav.tsx, BackOffice/src/Dashboard/index.tsx
make the dashboard dynamic in new customer count and active ones
=> [MES-59] make the dashboard dynamic
